server:
  port: 8084

spring:
  data:
    mongodb:
      database: clients
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
logging:
   config: logback.xml
